#!/bin/bash

# Quick Start - Build and Test Commands for Incidents Management App
# This script provides quick commands for testing on mobile and web

echo "================================"
echo "Incidents Management App"
echo "Mobile & Web Testing Guide"
echo "================================"
echo ""

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}📱 MOBILE TESTING${NC}"
echo "================="
echo ""
echo "Android Device/Emulator:"
echo -e "${GREEN}flutter run${NC}"
echo ""
echo "iOS Simulator/Device:"
echo -e "${GREEN}flutter run -d ios${NC}"
echo ""
echo "List connected devices:"
echo -e "${GREEN}flutter devices${NC}"
echo ""

echo -e "${BLUE}🌐 WEB TESTING${NC}"
echo "=============="
echo ""
echo "Chrome (default):"
echo -e "${GREEN}flutter run -d chrome${NC}"
echo ""
echo "Firefox:"
echo -e "${GREEN}flutter run -d firefox${NC}"
echo ""
echo "Safari (macOS):"
echo -e "${GREEN}flutter run -d safari${NC}"
echo ""
echo "Edge:"
echo -e "${GREEN}flutter run -d edge${NC}"
echo ""

echo -e "${BLUE}🔨 BUILD FOR PRODUCTION${NC}"
echo "======================="
echo ""
echo "Android APK:"
echo -e "${GREEN}flutter build apk${NC}"
echo ""
echo "Android App Bundle (Play Store):"
echo -e "${GREEN}flutter build appbundle${NC}"
echo ""
echo "iOS Build:"
echo -e "${GREEN}flutter build ios${NC}"
echo ""
echo "Web Build (Release):"
echo -e "${GREEN}flutter build web --release${NC}"
echo ""

echo -e "${BLUE}📊 TESTING RESPONSIVE DESIGN${NC}"
echo "============================="
echo ""
echo "1. Test on Multiple Devices:"
echo "   - Mobile phone (375×667 or similar)"
echo "   - Tablet (600×1024)"
echo "   - Desktop (1920×1080)"
echo ""
echo "2. Test Orientations:"
echo "   - Portrait mode"
echo "   - Landscape mode"
echo ""
echo "3. For Web - Use Chrome DevTools:"
echo "   - Open DevTools (F12)"
echo "   - Click device toolbar (Ctrl+Shift+M)"
echo "   - Select different devices to test"
echo ""

echo -e "${BLUE}🧹 CLEANING & MAINTENANCE${NC}"
echo "=========================="
echo ""
echo "Clean project:"
echo -e "${GREEN}flutter clean${NC}"
echo ""
echo "Get dependencies:"
echo -e "${GREEN}flutter pub get${NC}"
echo ""
echo "Analyze code:"
echo -e "${GREEN}flutter analyze${NC}"
echo ""

echo -e "${YELLOW}💡 TIPS${NC}"
echo "======"
echo "• Press 'w' in terminal while running to open Chrome DevTools"
echo "• Use '--profile' flag for performance testing: flutter run --profile"
echo "• Clear cache for web: Ctrl+Shift+Delete in browser"
echo "• Test with 'flutter run -d chrome --web-port=5000' for custom port"
echo ""
echo "Happy Testing! 🚀"
