// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAharYe12biNaaz7voJ7EL-24disKIMLb4',
    appId: '1:818149125918:web:2c287dc473370f3e95230f',
    messagingSenderId: '818149125918',
    projectId: 'risk-manamgment',
    authDomain: 'risk-manamgment.firebaseapp.com',
    storageBucket: 'risk-manamgment.firebasestorage.app',
    measurementId: 'G-VTB7GB84Y0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGZbja5Sg_nXKANy955_jCPZmkI03oOP8',
    appId: '1:818149125918:android:e180003c80768c6795230f',
    messagingSenderId: '818149125918',
    projectId: 'risk-manamgment',
    storageBucket: 'risk-manamgment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmL6DubkaRsht3IOigURmnI3iBCLX1CFk',
    appId: '1:818149125918:ios:c9c9c5c0f3b7c96795230f',
    messagingSenderId: '818149125918',
    projectId: 'risk-manamgment',
    storageBucket: 'risk-manamgment.firebasestorage.app',
    iosBundleId: 'com.example.incidentsManagment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmL6DubkaRsht3IOigURmnI3iBCLX1CFk',
    appId: '1:818149125918:ios:c9c9c5c0f3b7c96795230f',
    messagingSenderId: '818149125918',
    projectId: 'risk-manamgment',
    storageBucket: 'risk-manamgment.firebasestorage.app',
    iosBundleId: 'com.example.incidentsManagment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs8f6PWT-jmqEEwan_edxoE6yJY38HVpw',
    appId: '1:818149125918:web:28ee7fbc68785d3495230f',
    messagingSenderId: '818149125918',
    projectId: 'risk-manamgment',
    authDomain: 'risk-manamgment.firebaseapp.com',
    storageBucket: 'risk-manamgment.firebasestorage.app',
    measurementId: 'G-QCTE0TTVJ3',
  );
}
